apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer
        image: gabrielcamisadez/analyzer:latest
        ports:
        - containerPort: 5000


